### ISSUE TITLE
Performance of the C2Rust output Rust code?

### ISSUE THREAD

**Issue by JOE1994** [ZiCog/loop_blocking#1]
Hello, and Thank you for sharing the repo! 😃

May I ask you a quick question?
Does `performance.txt` contain performance statistics of the `C2Rust` output Rust code ??

![image](https://user-images.githubusercontent.com/10286488/73950370-d0fba300-48c9-11ea-8a6e-8b61e2f97f49.png)

**Comment by ZiCog** [comment]
Hi, Looking at performance.txt now it does seem rather confusing.

I will have to find time to revisit those results. Perhaps at the weekend.

**Comment by ZiCog** [comment]
You are right. You have labeled the c2rust output correctly.

I have tweaked the message output to make that clear and updated performance.txt.

If you can find a way to get the rust code (Not rust to C) to perform well on ARM that would be great.

**Comment by JOE1994** [comment]
@ZiCog Thanks for the update! 😃 May I ask which *ARM aarch64* machine you used for testing?
Unfortunately my PCs are all x86 machines, but I'll try to get access to an *ARM aarch64* machine !

**Comment by ZiCog** [comment]
I was running on a Raspberry Pi 3 and Debian. But I have a 64 bit kernel installed. I build and run 64 bit code under a 64 bit shell in there.

I just recently got hold of Now a Jetson Nano. You remind me I should repeat these experiments on that. Thanks.
